import 'package:http/http.dart' as http;
import 'dart:convert';

import '../../Locale_Memory/save_user_info_locally.dart';
import '../../const/urls.dart';

Future updateClient(
    String id,
    String reference,
    String showOnPos,
    String grantedDiscount,
    String isBlocked,
    String clientType,
    String name,
    String clientNumber,
    String country,
    String city,
    String state,
    String zip,
    String street,
    String floorBldg,
    String jobPosition,
    String phoneCode,
    String phone,
    String mobileCode,
    String mobile,
    String email,
    String title,
    String tags,
    String taxId,
    String website,
    String addressType,
    String contactName,
    String countryContact,
    String cityContact,
    String stateContact,
    String zipContact,
    String streetContact,
    String phoneContactCode,
    String phoneContact,
    String mobileContactCode,
    String mobileContact,
    String emailContact,
    String salesperson,
    String paymentTerm,
    String pricelist,
    String internalNote,
    String clientCompany,
    ) async {
  final uri = Uri.parse('$kClientUrl/$id');
  String token = await getAccessTokenFromPref();
  var response = await http.put(uri, headers: {
    "Accept": "application/json",
    "Authorization": "Bearer $token"
  }, body: {
    "showOnPos": showOnPos,
    "grantedDiscount": grantedDiscount,
    "isBlocked": isBlocked,
    "clientType": clientType,
    "name": name,
    "reference": reference,
    "clientNumber": clientNumber,
    "country": country,
    "city": city,
    "state": state,
    "zip": zip,
    "street": street,
    "floorBldg": floorBldg,
    "jobPosition": jobPosition,
    "phoneCode": phoneCode,
    "phone": phone,
    "mobileCode": mobileCode,
    "mobile": mobile,
    "email": email,
    "title": title,
    "tags": tags,
    "taxId": taxId,
    "website": website,
    "addressType": addressType,
    "contactName": contactName,
    "countryContact": countryContact,
    "cityContact": cityContact,
    "stateContact": stateContact,
    "zipContact": zipContact,
    "streetContact": streetContact,
    "phoneContactCode": phoneContactCode,
    'phoneContact': phoneContact,
    'mobileContactCode': mobileContactCode,
    'mobileContact': mobileContact,
    'emailContact': emailContact,
    'salesperson': salesperson,
    'paymentTerm': paymentTerm,
    'pricelist': pricelist,
    'internalNote': internalNote,
    'clientCompany': clientCompany,
  });

  var p = json.decode(response.body);
  // print('updated $p');
  return p; //p['success']==true
}
